### ISSUE TITLE
接口地址 被 快递100 关闭了

### ISSUE THREAD

**Issue by yangguangwuwu** [lazywe/logistics#2]

**Comment by lazywe** [comment]
已经处理了，
但是不建议使用不定义快递类型的方式，
因为目前不同物流有订单号好重复问题，
建议指定物流的方式

**Comment by lazywe** [comment]
没问题我就关闭了。

**Comment by yangguangwuwu** [comment]
这个地址 没用了  官方网页都显示不了物流 信息

**Comment by yangguangwuwu** [comment]
查出来的数据 是空的

**Comment by yangguangwuwu** [comment]
快递100把这个地址 关了  现在他给 百度 的能用    他官网的 都查不出来 https://www.kuaidi100.com   
YT4051862265911 圆通的

**Comment by yangguangwuwu** [comment]
所以你类里这个地址查的数据 也是 空的 这个 单号是 收货的 单号 有物流信息的  快递鸟能有数据
还有快递100给百度  搜索结果页的 是 有数据的

**Comment by lazywe** [comment]
应该是ip被封禁了，你F12看一下

**Comment by lazywe** [comment]
我觉得应该是受限制了，此方案可能已经行不通了，所以建议接正规渠道

**Comment by yangguangwuwu** [comment]
不知道 通过百度的 时效是多久  感觉 可以通过百度的

**Comment by yangguangwuwu** [comment]
https://sp0.baidu.com/9_Q4sjW91Qh3otqbppnN2DJv/pae/channel/data/asyncqury?cb=jQuery110205632685617365383_1567154938657&appid=4001&com=yuantong&nu=yt4051862265911&vcode=&token=&_=1567154938661
